on:
    push:
      branches:
        - main
permissions:
  contents: write
  packages: write
  pull-requests: write

name: Release & Publish @christopherhex/cordova-test-plugin
jobs:
  publish-gpr:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - uses: actions/setup-node@v3
        with:
          node-version: '16.x'
          registry-url: https://npm.pkg.github.com/
          scope: '@christopherhex'
      - run: npm publish @christopherhex/cordova-test-plugin --access public
        env:
          NODE_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}
  